-- Run this in the Supabase SQL editor (Project -> SQL Editor -> New query)
-- to create the subscribers table used by the newsletter pipeline.

create table if not exists public.subscribers (
    id            bigint generated by default as identity primary key,
    email         text not null unique,
    status        text not null default 'active' check (status in ('active', 'unsubscribed')),
    subscribed_at timestamptz not null default now()
);

-- Speeds up the "active subscribers" query used by send_email.py
create index if not exists idx_subscribers_status on public.subscribers (status);

-- Enable Row Level Security. The pipeline uses the SERVICE_ROLE key, which
-- bypasses RLS entirely, so no policies are strictly required for it to
-- work — but RLS should stay ON so the anon/public key (if ever exposed
-- in a signup form) cannot read other people's emails.
alter table public.subscribers enable row level security;

-- Optional: allow anonymous inserts only (e.g. a public signup form using
-- the anon key), but never allow anonymous selects/updates/deletes.
-- Uncomment if you build a public subscribe form with the anon key:
--
-- create policy "Allow anonymous signups"
--   on public.subscribers
--   for insert
--   to anon
--   with check (true);
