#!/usr/bin/env python3
"""
supabase_client.py - Minimal Supabase REST (PostgREST) helper

Provides just enough functionality for the newsletter pipeline to read
active subscribers from, and add new subscribers to, a Supabase Postgres
table — without pulling in the full `supabase-py` SDK (and its many
dependencies). Uses plain HTTP via `requests`, which is already a
project dependency.

Required environment variables:
    SUPABASE_URL          e.g. https://xxxxxxxx.supabase.co
    SUPABASE_SERVICE_KEY  Service role key (server-side only, NEVER expose
                          this to a browser/client). Used so the pipeline
                          can read all subscribers regardless of RLS.

Expected table schema (see supabase_schema.sql for the full DDL):

    create table public.subscribers (
        id            bigint generated by default as identity primary key,
        email         text unique not null,
        status        text not null default 'active',  -- 'active' | 'unsubscribed'
        subscribed_at timestamptz not null default now()
    );
"""

import logging
import os
from typing import List, Optional

import requests
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger("supabase_client")

SUPABASE_URL = (os.getenv("SUPABASE_URL") or "").rstrip("/")
SUPABASE_SERVICE_KEY = os.getenv("SUPABASE_SERVICE_KEY")
SUBSCRIBERS_TABLE = os.getenv("SUPABASE_SUBSCRIBERS_TABLE", "subscribers")

REQUEST_TIMEOUT = 15


def is_configured() -> bool:
    """Whether Supabase credentials are present in the environment."""
    return bool(SUPABASE_URL and SUPABASE_SERVICE_KEY)


def _headers() -> dict:
    return {
        "apikey": SUPABASE_SERVICE_KEY,
        "Authorization": f"Bearer {SUPABASE_SERVICE_KEY}",
        "Content-Type": "application/json",
    }


def get_active_subscribers() -> Optional[List[str]]:
    """
    Fetch all subscriber emails with status='active' from Supabase.

    Returns:
        A sorted, deduplicated list of lowercase emails, or None if the
        request failed (so callers can decide how to handle the error).
    """
    if not is_configured():
        logger.warning("⚠️ Supabase not configured (SUPABASE_URL / SUPABASE_SERVICE_KEY missing).")
        return None

    url = f"{SUPABASE_URL}/rest/v1/{SUBSCRIBERS_TABLE}"
    params = {"select": "email", "status": "eq.active"}

    try:
        resp = requests.get(url, headers=_headers(), params=params, timeout=REQUEST_TIMEOUT)
        resp.raise_for_status()
        rows = resp.json()
        emails = sorted({row["email"].strip().lower() for row in rows if row.get("email")})
        logger.info(f"👥 Loaded {len(emails)} active subscribers from Supabase")
        return emails
    except requests.RequestException as e:
        logger.error(f"💥 Failed to fetch subscribers from Supabase: {e}")
        return None


def add_subscriber(email: str) -> bool:
    """
    Insert (or reactivate) a subscriber by email. Uses upsert so re-running
    is safe for already-existing rows.
    """
    if not is_configured():
        logger.warning("⚠️ Supabase not configured (SUPABASE_URL / SUPABASE_SERVICE_KEY missing).")
        return False

    url = f"{SUPABASE_URL}/rest/v1/{SUBSCRIBERS_TABLE}"
    headers = _headers()
    headers["Prefer"] = "resolution=merge-duplicates"

    payload = {"email": email.strip().lower(), "status": "active"}

    try:
        resp = requests.post(url, headers=headers, json=payload, timeout=REQUEST_TIMEOUT)
        resp.raise_for_status()
        return True
    except requests.RequestException as e:
        logger.error(f"💥 Failed to add subscriber {email} to Supabase: {e}")
        return False


def unsubscribe(email: str) -> bool:
    """Mark a subscriber's status as 'unsubscribed' (soft delete)."""
    if not is_configured():
        logger.warning("⚠️ Supabase not configured (SUPABASE_URL / SUPABASE_SERVICE_KEY missing).")
        return False

    url = f"{SUPABASE_URL}/rest/v1/{SUBSCRIBERS_TABLE}"
    params = {"email": f"eq.{email.strip().lower()}"}
    payload = {"status": "unsubscribed"}

    try:
        resp = requests.patch(url, headers=_headers(), params=params, json=payload, timeout=REQUEST_TIMEOUT)
        resp.raise_for_status()
        return True
    except requests.RequestException as e:
        logger.error(f"💥 Failed to unsubscribe {email} in Supabase: {e}")
        return False
